# -*- Makefile -*-
# See ../Makefile-include

DEPLOY_FILES:=	building-at-uw-cse.md \
		common-tasks.md \
		index.md \
		javascriptcore-internals.md \
		profiler-internals.md \
		README \
		repository.md \
		webcore-internals.md \
		webkit-runloop.md \
		webinspector-internals.md

DIRECTORY:=developer
include ../Makefile-include