# -*- Makefile -*-
# See ../Makefile-include

DEPLOY_FILES:=droid.js toc.js jquery-1.5.2.min.js shAutoloader.js shBrushCpp.js shBrushCss.js shBrushJScript.js shBrushJava.js shBrushPerl.js shBrushPlain.js shBrushXml.js shCore.js

DIRECTORY:=js
include ../Makefile-include