# -*- Makefile -*-
# See ../Makefile-include

DEPLOY_FILES:=main.css shCore.css shCoreDefault.css shCoreEmacs.css shThemeDefault.css shThemeEmacs.css style.css

DIRECTORY:=css
include ../Makefile-include