# -*- Makefile -*-
# See ../Makefile-include

DEPLOY_FILES:=sss-logo.jpg uwcse-logo.jpg vis_one.png vis_two.png vis_three.png state_one.png state_two.png state_three.png

DIRECTORY:=images
include ../Makefile-include